package com.example.cms.mock;


import com.example.cms.cartitem.domain.CartItem;
import com.example.cms.cartitem.service.port.CartItemRepository;



import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import java.util.concurrent.atomic.AtomicLong;

public class FakeCartItemRepository implements CartItemRepository {

    private final AtomicLong autoGeneratedId =new AtomicLong(0);
    private final List<CartItem> data = new ArrayList<>();

    @Override
    public CartItem save(CartItem cartItem) {
        if (cartItem.getId() == null || cartItem.getId() == 0){
            CartItem save = CartItem.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .cart(cartItem.getCart())
                    .item(cartItem.getItem())
                    .price(cartItem.getPrice())
                    .count(cartItem.getCount())
                    .build();
            data.add(save);
            return save;
        } else {
            data.removeIf(test -> Objects.equals(test.getId(),cartItem.getId()));
            data.add(cartItem);
            return cartItem;
        }
    }



}
